packages:
  - '.'
allowBuilds:
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - '@latex2js/macros@3.2.0'
  - '@latex2js/pstricks@4.2.0'
  - '@latex2js/settings@4.2.0'
  - '@latex2js/utils@4.2.0'
  - latex2js@4.3.1
  - latex2react@4.3.1
  - mathjaxjs-react@4.2.0
  - mathjaxjs@4.2.0
overrides:
  '@types/react': 19.2.10
  '@types/react-dom': 19.2.3
